### ISSUE TITLE
下一页404 next 

### ISSUE THREAD

**Issue by apgmer** [LzIManD/FlarumApiDocs#1]
请求这个地址

`http://bbs.lzqstd.net/api/discussions?include=startUser,lastUser,startPost,tags&&page[offset]=20`

获取的 next 链接是：
`http://bbs.lzqstd.net/discussions?include=startUser%2ClastUser%2CstartPost%2Ctags&page%5Boffset%5D=40`

返回404 

应该返回链接是
 `http://bbs.lzqstd.net/api/discussions?include=startUser%2ClastUser%2CstartPost%2Ctags&page%5Boffset%5D=40`

**Comment by apgmer** [comment]
好吧   `http://discuss.flarum.org.cn/`  的api也是这个问题

**Comment by LzIManD** [comment]
我这可以的

Request URL:http://bbs.lzqstd.net/api/discussions?include=startUser%2ClastUser%2CstartPost%2Ctags&page%5Boffset%5D=40
Request Method:GET

HTTP/1.1 200 OK
Server: nginx/1.8.0
Date: Tue, 29 Dec 2015 03:43:47 GMT
Content-Type: application/vnd.api+json
Content-Length: 94598
Connection: keep-alive
X-Powered-By: PHP/5.5.9-1ubuntu4.14

**Comment by apgmer** [comment]
你返回的链接  没有 /api 所以 404 你仔细看看  
```
"links": {
"first": "http://bbs.lzqstd.net/discussions?include=startUser%2ClastUser%2CstartPost%2Ctags",
"prev": "http://bbs.lzqstd.net/discussions?include=startUser%2ClastUser%2CstartPost%2Ctags",
"next": "http://bbs.lzqstd.net/discussions?include=startUser%2ClastUser%2CstartPost%2Ctags&page%5Boffset%5D=40"
}
```

**Comment by LzIManD** [comment]
好吧，这个问题呀，我改下源码

**Comment by LzIManD** [comment]
大概找到问题了，考完下午这个试处理下

**Comment by LzIManD** [comment]
$document->addPaginationLinks(
            $this->url->toRoute('discussions.index'),
            $request->getQueryParams(),
            $offset,
            $limit,
            $results->areMoreResults() ? null : 0
        );

**Comment by LzIManD** [comment]
ok
