### ISSUE TITLE
发帖怎么搞？

### ISSUE THREAD

**Issue by apgmer** [LzIManD/FlarumApiDocs#2]
头部设置了
`
"Authorization": "xxxxxxxxxxxxxxxxxxxxxxxxx","Content-Type": "application/vnd.api+json"
`

然后？数据格式 我是这样写的

```
["data": ["relationships": {
    tags =     {
        data =         (
                        {
                id = 22;
                type = tags;
            },
                        {
                id = 11;
                type = tags;
            }
        );
    };
}, "attributes": {
    content = "\U53d1\U5e16\U6d4b\U8bd5c";
    title = "\U53d1\U5e16\U6d4b\U8bd5";
}, "type": discussions]]

```
上面的数据是要转化为json 的

然后 到底是哪里不对？服务器一直返回error，求正确的数据格式

**Comment by apgmer** [comment]
知道了，header 应该是这样的：
` "Authorization": "Token drafOZS2OcMQfpvuKMsV8JbPClfo0WlIf93iza1z", "Content-Type": "application/vnd.api+json" `

**Comment by LzIManD** [comment]
没考试的日子果然好爽，哎
